# Generated by Django 3.0.14 on 2021-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0085_merge_20210415_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hidden_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
