# Generated by Django 3.0.14 on 2021-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0086_singleentitygroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleentitygroup",
            name="org_units",
            field=models.ManyToManyField(blank=True, related_name="single_entity_group", to="iaso.OrgUnit"),
        ),
    ]
