# Generated by Django 3.0.14 on 2021-05-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0087_auto_20210521_1104'),
        ('iaso', '0086_add_version_constraints'),
    ]

    operations = [
    ]
