# Generated by Django 3.1.12 on 2021-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0102_merge_20210712_1014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importgpkg",
            name="version_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
