# Generated by Django 3.0.14 on 2021-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0086_group_hidden_at'),
        ('polio', '0004_auto_20210505_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='iaso.Group'),
        ),
    ]
