# Generated by Django 3.0.14 on 2021-06-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0006_merge_20210601_1708"),
        ("polio", "0006_merge_20210602_1150"),
    ]

    operations = []
